SELECT 
	p.NAMA as "NAMA PELANGGAN", 
    SUM(t.JUMLAH_BARANG) as "JUMLAH",
    SUM(b.HARGA * t.JUMLAH_BARANG) as "TOTAL"
FROM transaksi t
JOIN pelanggan p ON t.KODE_PELANGGAN = p.KODE
JOIN barang b on t.KODE_BARANG = b.KODE
GROUP BY t.KODE_PELANGGAN
ORDER BY p.NAMA ASC;